cluster_name: Kubernetes Cluster

# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  control_ip: 192.168.56.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 2
    cpu: 1
    memory: 2048
software:
  box: bento/ubuntu-24.04
  calico: 3.26.0
  kubernetes: 1.31.0-*


